/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package calculatrice;
import java.util.Stack;
/**
 *
 * @author Asus
 */
public class calculatrice_1 extends javax.swing.JFrame {

    /**
     * Creates new form calculatrice_1
     */
    public calculatrice_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        B_C = new javax.swing.JButton();
        B_equal = new javax.swing.JButton();
        B_fois = new javax.swing.JButton();
        B_5 = new javax.swing.JButton();
        B_8 = new javax.swing.JButton();
        B_9 = new javax.swing.JButton();
        B_7 = new javax.swing.JButton();
        B_4 = new javax.swing.JButton();
        B_moin = new javax.swing.JButton();
        B_6 = new javax.swing.JButton();
        B_plus = new javax.swing.JButton();
        B_1 = new javax.swing.JButton();
        B_0 = new javax.swing.JButton();
        B_3 = new javax.swing.JButton();
        B_2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        B_div = new javax.swing.JButton();

        jLabel3.setBackground(new java.awt.Color(0, 0, 204));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(253, 199, 26));

        jPanel2.setBackground(new java.awt.Color(40, 49, 60));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setPreferredSize(new java.awt.Dimension(280, 430));

        B_C.setBackground(new java.awt.Color(79, 60, 242));
        B_C.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        B_C.setForeground(new java.awt.Color(255, 255, 255));
        B_C.setText("C");
        B_C.setBorder(null);
        B_C.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        B_C.setPreferredSize(new java.awt.Dimension(60, 60));
        B_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_CActionPerformed(evt);
            }
        });

        B_equal.setBackground(new java.awt.Color(255, 0, 0));
        B_equal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        B_equal.setForeground(new java.awt.Color(255, 255, 255));
        B_equal.setText("=");
        B_equal.setBorder(null);
        B_equal.setPreferredSize(new java.awt.Dimension(60, 60));
        B_equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_equalActionPerformed(evt);
            }
        });

        B_fois.setBackground(new java.awt.Color(79, 60, 242));
        B_fois.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        B_fois.setForeground(new java.awt.Color(255, 255, 255));
        B_fois.setText("*");
        B_fois.setBorder(null);
        B_fois.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        B_fois.setPreferredSize(new java.awt.Dimension(60, 60));
        B_fois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_foisActionPerformed(evt);
            }
        });

        B_5.setBackground(new java.awt.Color(79, 60, 242));
        B_5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        B_5.setForeground(new java.awt.Color(255, 255, 255));
        B_5.setText("5");
        B_5.setBorder(null);
        B_5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        B_5.setPreferredSize(new java.awt.Dimension(60, 60));
        B_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_5ActionPerformed(evt);
            }
        });

        B_8.setBackground(new java.awt.Color(79, 60, 242));
        B_8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        B_8.setForeground(new java.awt.Color(255, 255, 255));
        B_8.setText("8");
        B_8.setBorder(null);
        B_8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        B_8.setPreferredSize(new java.awt.Dimension(60, 60));
        B_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_8ActionPerformed(evt);
            }
        });

        B_9.setBackground(new java.awt.Color(79, 60, 242));
        B_9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        B_9.setForeground(new java.awt.Color(255, 255, 255));
        B_9.setText("9");
        B_9.setBorder(null);
        B_9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        B_9.setPreferredSize(new java.awt.Dimension(60, 60));
        B_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_9ActionPerformed(evt);
            }
        });

        B_7.setBackground(new java.awt.Color(79, 60, 242));
        B_7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        B_7.setForeground(new java.awt.Color(255, 255, 255));
        B_7.setText("7");
        B_7.setBorder(null);
        B_7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        B_7.setPreferredSize(new java.awt.Dimension(60, 60));
        B_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_7ActionPerformed(evt);
            }
        });

        B_4.setBackground(new java.awt.Color(79, 60, 242));
        B_4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        B_4.setForeground(new java.awt.Color(255, 255, 255));
        B_4.setText("4");
        B_4.setBorder(null);
        B_4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        B_4.setPreferredSize(new java.awt.Dimension(60, 60));
        B_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_4ActionPerformed(evt);
            }
        });

        B_moin.setBackground(new java.awt.Color(79, 60, 242));
        B_moin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        B_moin.setForeground(new java.awt.Color(255, 255, 255));
        B_moin.setText("-");
        B_moin.setBorder(null);
        B_moin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        B_moin.setPreferredSize(new java.awt.Dimension(60, 60));
        B_moin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_moinActionPerformed(evt);
            }
        });

        B_6.setBackground(new java.awt.Color(79, 60, 242));
        B_6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        B_6.setForeground(new java.awt.Color(255, 255, 255));
        B_6.setText("6");
        B_6.setBorder(null);
        B_6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        B_6.setPreferredSize(new java.awt.Dimension(60, 60));
        B_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_6ActionPerformed(evt);
            }
        });

        B_plus.setBackground(new java.awt.Color(79, 60, 242));
        B_plus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        B_plus.setForeground(new java.awt.Color(255, 255, 255));
        B_plus.setText("+");
        B_plus.setBorder(null);
        B_plus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        B_plus.setPreferredSize(new java.awt.Dimension(60, 60));
        B_plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_plusActionPerformed(evt);
            }
        });

        B_1.setBackground(new java.awt.Color(79, 60, 242));
        B_1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        B_1.setForeground(new java.awt.Color(255, 255, 255));
        B_1.setText("1");
        B_1.setBorder(null);
        B_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        B_1.setPreferredSize(new java.awt.Dimension(60, 60));
        B_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_1ActionPerformed(evt);
            }
        });

        B_0.setBackground(new java.awt.Color(79, 60, 242));
        B_0.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        B_0.setForeground(new java.awt.Color(255, 255, 255));
        B_0.setText("0");
        B_0.setBorder(null);
        B_0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        B_0.setPreferredSize(new java.awt.Dimension(60, 60));
        B_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_0ActionPerformed(evt);
            }
        });

        B_3.setBackground(new java.awt.Color(79, 60, 242));
        B_3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        B_3.setForeground(new java.awt.Color(255, 255, 255));
        B_3.setText("3");
        B_3.setBorder(null);
        B_3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        B_3.setPreferredSize(new java.awt.Dimension(60, 60));
        B_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_3ActionPerformed(evt);
            }
        });

        B_2.setBackground(new java.awt.Color(79, 60, 242));
        B_2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        B_2.setForeground(new java.awt.Color(255, 255, 255));
        B_2.setText("2");
        B_2.setBorder(null);
        B_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        B_2.setPreferredSize(new java.awt.Dimension(60, 60));
        B_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_2ActionPerformed(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(255, 255, 204));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jLabel1ComponentHidden(evt);
            }
        });

        B_div.setBackground(new java.awt.Color(79, 60, 242));
        B_div.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        B_div.setForeground(new java.awt.Color(255, 255, 255));
        B_div.setText("/");
        B_div.setBorder(null);
        B_div.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        B_div.setPreferredSize(new java.awt.Dimension(60, 60));
        B_div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_divActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(B_C, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(B_4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(B_5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(B_1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(B_2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(B_7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(B_8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(B_0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(B_9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(B_6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(B_3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(B_plus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(B_fois, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(B_moin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(B_div, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(B_equal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_C, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_div, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_fois, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_moin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(B_plus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(B_3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(B_2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(B_1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_equal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(334, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(278, 278, 278))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(237, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void B_CActionPerformed(java.awt.event.ActionEvent evt) {                                    
     jTextField1.setText("") ;
     jLabel1.setText("");
        
    }                                   

    private void B_divActionPerformed(java.awt.event.ActionEvent evt) {                                      
        jLabel1.setText(jLabel1.getText()+ B_div.getText()) ;
    }                                     

    private void B_foisActionPerformed(java.awt.event.ActionEvent evt) {                                       
        jLabel1.setText(jLabel1.getText()+ B_fois.getText()) ;
    }                                      

    private void B_5ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        jLabel1.setText(jLabel1.getText()+ B_5.getText()) ;
    }                                   

    private void B_8ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        jLabel1.setText(jLabel1.getText()+ B_8.getText()) ;
    }                                   

    private void B_9ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        jLabel1.setText(jLabel1.getText()+ B_9.getText()) ;
    }                                   

    private void B_7ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
        jLabel1.setText(jLabel1.getText()+ B_7.getText()) ;
    }                                   

    private void B_4ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
        jLabel1.setText(jLabel1.getText()+ B_4.getText()) ;
    }                                   

    private void B_moinActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        jLabel1.setText(jLabel1.getText()+ B_moin.getText()) ;
    }                                      

    private void B_6ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        jLabel1.setText(jLabel1.getText()+ B_6.getText()) ;
    }                                   

    private void B_plusActionPerformed(java.awt.event.ActionEvent evt) {                                       
        jLabel1.setText(jLabel1.getText()+ B_plus.getText()) ;
    }                                      

    private void B_1ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        jLabel1.setText(jLabel1.getText()+ B_1.getText()) ;
    }                                   

    private void B_0ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        jLabel1.setText(jLabel1.getText()+ B_0.getText()) ;
    }                                   

    private void B_3ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        jLabel1.setText(jLabel1.getText()+ B_3.getText()) ;
    }                                   

    private void B_2ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        jLabel1.setText(jLabel1.getText()+ B_2.getText()) ;
    }                                   

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void B_equalActionPerformed(java.awt.event.ActionEvent evt) {                                        
        jTextField1.setText(Integer.toString(EvaluateString.evaluate(jLabel1.getText())));
        jLabel1.setText(jTextField1.getText());
        
       
    }                                       

    private void jLabel1ComponentHidden(java.awt.event.ComponentEvent evt) {                                        
        
    }                                       

    public class EvaluateCE{
    public static int lastposition(String[] ch){
    int x;
for(int i=0;i<ch.length;i++){
    if(ch[i]=="+" || ch[i]=="-" || ch[i]=="*" || ch[i]=="/" ){
        x=i;
    }   
}
        return x;
}
}
  
/* A Java program to evaluate a
given expression where tokens
are separated by space.
*/
public class EvaluateString
{
    
	public static int evaluate(String expression)
	{
		char[] tokens = expression.toCharArray();

		// Stack for numbers: 'values'
		Stack<Integer> values = new
							Stack<Integer>();

		// Stack for Operators: 'ops'
		Stack<Character> ops = new
							Stack<Character>();

		for (int i = 0; i < tokens.length; i++)
		{
			
			// Current token is a
			// whitespace, skip it
			if (tokens[i] == ' ')
				continue;

			// Current token is a number,
			// push it to stack for numbers
			if (tokens[i] >= '0' &&
				tokens[i] <= '9')
			{
				StringBuffer sbuf = new
							StringBuffer();
				
				// There may be more than one
				// digits in number
				while (i < tokens.length &&
						tokens[i] >= '0' &&
						tokens[i] <= '9')
					sbuf.append(tokens[i++]);
				values.push(Integer.parseInt(sbuf.
									toString()));
			
				// right now the i points to
				// the character next to the digit,
				// since the for loop also increases
				// the i, we would skip one
				// token position; we need to
				// decrease the value of i by 1 to
				// correct the offset.
				i--;
			}

			// Current token is an opening brace,
			// push it to 'ops'
			else if (tokens[i] == '(')
				ops.push(tokens[i]);

			// Closing brace encountered,
			// solve entire brace
			else if (tokens[i] == ')')
			{
				while (ops.peek() != '(')
				values.push(applyOp(ops.pop(),
								values.pop(),
								values.pop()));
				ops.pop();
			}

			// Current token is an operator.
			else if (tokens[i] == '+' ||
					tokens[i] == '-' ||
					tokens[i] == '*' ||
						tokens[i] == '/')
			{
				// While top of 'ops' has same
				// or greater precedence to current
				// token, which is an operator.
				// Apply operator on top of 'ops'
				// to top two elements in values stack
				while (!ops.empty() &&
					hasPrecedence(tokens[i],
									ops.peek()))
				values.push(applyOp(ops.pop(),
								values.pop(),
								values.pop()));

				// Push current token to 'ops'.
				ops.push(tokens[i]);
			}
		}

		// Entire expression has been
		// parsed at this point, apply remaining
		// ops to remaining values
		while (!ops.empty())
			values.push(applyOp(ops.pop(),
							values.pop(),
						values.pop()));

		// Top of 'values' contains
		// result, return it
		return values.pop();
	}

	// Returns true if 'op2' has higher
	// or same precedence as 'op1',
	// otherwise returns false.
	public static boolean hasPrecedence(
						char op1, char op2)
	{
		if (op2 == '(' || op2 == ')')
			return false;
		if ((op1 == '*' || op1 == '/') &&
			(op2 == '+' || op2 == '-'))
			return false;
		else
			return true;
	}

	// A utility method to apply an
	// operator 'op' on operands 'a'
	// and 'b'. Return the result.
	public static int applyOp(char op,
						int b, int a)
	{
		switch (op)
		{
		case '+':
			return a + b;
		case '-':
			return a - b;
		case '*':
			return a * b;
		case '/':
			if (b == 0)
				throw new
				UnsupportedOperationException(
					"Cannot divide by zero");
			return a / b;
		}
		return 0;
	}	// Driver method to test above methods
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculatrice_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculatrice_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculatrice_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculatrice_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculatrice_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton B_0;
    private javax.swing.JButton B_1;
    private javax.swing.JButton B_2;
    private javax.swing.JButton B_3;
    private javax.swing.JButton B_4;
    private javax.swing.JButton B_5;
    private javax.swing.JButton B_6;
    private javax.swing.JButton B_7;
    private javax.swing.JButton B_8;
    private javax.swing.JButton B_9;
    private javax.swing.JButton B_C;
    private javax.swing.JButton B_div;
    private javax.swing.JButton B_equal;
    private javax.swing.JButton B_fois;
    private javax.swing.JButton B_moin;
    private javax.swing.JButton B_plus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration                   
}
